version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://api.bluehooper.com/api}
        - VITE_APP_NAME=${VITE_APP_NAME:-BlueHooper}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    container_name: bluehooper-frontend
    ports:
      - "${FRONTEND_PORT:-3006}:3006"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN:-localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3006"

networks:
  frontend-network:
    driver: bridge
    name: bluehooper-frontend-network