version: '3.8'

networks:
  k6:
    driver: bridge

services:
  influxdb:
    image: influxdb:1.8
    container_name: k6-influxdb
    networks:
      - k6
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - k6-influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    networks:
      - k6
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - k6-grafana-data:/var/lib/grafana
      - ./k6/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./k6/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6-runner
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - K6_INFLUXDB_USERNAME=k6
      - K6_INFLUXDB_PASSWORD=k6
    volumes:
      - ./k6/tests:/tests
      - ./k6/results:/results
    depends_on:
      - influxdb
    command: ["sleep", "3600"] # Keep container running

volumes:
  k6-influxdb-data:
  k6-grafana-data: